name: Flutter CI/CD

on:

  push:
    branches: [ ci/cd ]
  pull_request:
    branches: [ ci/cd ]


  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
      # Checks-out
      - uses: actions/checkout@v3
      
      # Setup Java (required for Flutter)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      
      # Setup Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
      
      # Get dependencies
      - name: Get dependencies
        run: flutter pub get

    
      - name: Build Apk
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      